dist: trusty
sudo: required
language: go
go: '1.x'
env:
  - PATH=/snap/bin:$PATH GO111MODULE=on
install:
  - make setup
  - sudo snap install snapcraft --classic
script:
  - make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - rm coverage.txt

notifications:
  email: false
